using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace DemoRobot.Models
{
    public class Formulario
    {
        [Key]
        public int id_formulario { get; set; }

        public int id_robot { get; set; }
        public string nombre_robot { get; set; }
        public int id_tarea { get; set; }
        public string nombre_tarea { get; set; }
        public int idhorario { get; set; }
        public Nullable<bool> l1 { get; set; }
        public Nullable<bool> l2 { get; set; }
        public Nullable<bool> l3 { get; set; }
        public Nullable<bool> l4 { get; set; }
        public Nullable<bool> l5 { get; set; }
        public Nullable<bool> l6 { get; set; }
        public Nullable<bool> l7 { get; set; }
        public Nullable<bool> l8 { get; set; }
        public Nullable<bool> l9 { get; set; }
        public Nullable<bool> l10 { get; set; }
        public Nullable<bool> l11 { get; set; }
        public Nullable<bool> l12 { get; set; }
        public Nullable<bool> l13 { get; set; }
        public Nullable<bool> l14 { get; set; }
        public Nullable<bool> l15 { get; set; }
        public Nullable<bool> l16 { get; set; }
        public Nullable<bool> l17 { get; set; }
        public Nullable<bool> l18 { get; set; }
        public Nullable<bool> l19 { get; set; }
        public Nullable<bool> l20 { get; set; }
        public Nullable<bool> l21 { get; set; }
        public Nullable<bool> l22 { get; set; }
        public Nullable<bool> l23 { get; set; }
        public Nullable<bool> l24 { get; set; }
        public Nullable<bool> ma1 { get; set; }
        public Nullable<bool> ma2 { get; set; }
        public Nullable<bool> ma3 { get; set; }
        public Nullable<bool> ma4 { get; set; }
        public Nullable<bool> ma5 { get; set; }
        public Nullable<bool> ma6 { get; set; }
        public Nullable<bool> ma7 { get; set; }
        public Nullable<bool> ma8 { get; set; }
        public Nullable<bool> ma9 { get; set; }
        public Nullable<bool> ma10 { get; set; }
        public Nullable<bool> ma11 { get; set; }
        public Nullable<bool> ma12 { get; set; }
        public Nullable<bool> ma13 { get; set; }
        public Nullable<bool> ma14 { get; set; }
        public Nullable<bool> ma15 { get; set; }
        public Nullable<bool> ma16 { get; set; }
        public Nullable<bool> ma17 { get; set; }
        public Nullable<bool> ma18 { get; set; }
        public Nullable<bool> ma19 { get; set; }
        public Nullable<bool> ma20 { get; set; }
        public Nullable<bool> ma21 { get; set; }
        public Nullable<bool> ma22 { get; set; }
        public Nullable<bool> ma23 { get; set; }
        public Nullable<bool> ma24 { get; set; }
        public Nullable<bool> mi1 { get; set; }
        public Nullable<bool> mi2 { get; set; }
        public Nullable<bool> mi3 { get; set; }
        public Nullable<bool> mi4 { get; set; }
        public Nullable<bool> mi5 { get; set; }
        public Nullable<bool> mi6 { get; set; }
        public Nullable<bool> mi7 { get; set; }
        public Nullable<bool> mi8 { get; set; }
        public Nullable<bool> mi9 { get; set; }
        public Nullable<bool> mi10 { get; set; }
        public Nullable<bool> mi11 { get; set; }
        public Nullable<bool> mi12 { get; set; }
        public Nullable<bool> mi13 { get; set; }
        public Nullable<bool> mi14 { get; set; }
        public Nullable<bool> mi15 { get; set; }
        public Nullable<bool> mi16 { get; set; }
        public Nullable<bool> mi17 { get; set; }
        public Nullable<bool> mi18 { get; set; }
        public Nullable<bool> mi19 { get; set; }
        public Nullable<bool> mi20 { get; set; }
        public Nullable<bool> mi21 { get; set; }
        public Nullable<bool> mi22 { get; set; }
        public Nullable<bool> mi23 { get; set; }
        public Nullable<bool> mi24 { get; set; }
        public Nullable<bool> j1 { get; set; }
        public Nullable<bool> j2 { get; set; }
        public Nullable<bool> j3 { get; set; }
        public Nullable<bool> j4 { get; set; }
        public Nullable<bool> j5 { get; set; }
        public Nullable<bool> j6 { get; set; }
        public Nullable<bool> j7 { get; set; }
        public Nullable<bool> j8 { get; set; }
        public Nullable<bool> j9 { get; set; }
        public Nullable<bool> j10 { get; set; }
        public Nullable<bool> j11 { get; set; }
        public Nullable<bool> j12 { get; set; }
        public Nullable<bool> j13 { get; set; }
        public Nullable<bool> j14 { get; set; }
        public Nullable<bool> j15 { get; set; }
        public Nullable<bool> j16 { get; set; }
        public Nullable<bool> j17 { get; set; }
        public Nullable<bool> j18 { get; set; }
        public Nullable<bool> j19 { get; set; }
        public Nullable<bool> j20 { get; set; }
        public Nullable<bool> j21 { get; set; }
        public Nullable<bool> j22 { get; set; }
        public Nullable<bool> j23 { get; set; }
        public Nullable<bool> j24 { get; set; }
        public Nullable<bool> v1 { get; set; }
        public Nullable<bool> v2 { get; set; }
        public Nullable<bool> v3 { get; set; }
        public Nullable<bool> v4 { get; set; }
        public Nullable<bool> v5 { get; set; }
        public Nullable<bool> v6 { get; set; }
        public Nullable<bool> v7 { get; set; }
        public Nullable<bool> v8 { get; set; }
        public Nullable<bool> v9 { get; set; }
        public Nullable<bool> v10 { get; set; }
        public Nullable<bool> v11 { get; set; }
        public Nullable<bool> v12 { get; set; }
        public Nullable<bool> v13 { get; set; }
        public Nullable<bool> v14 { get; set; }
        public Nullable<bool> v15 { get; set; }
        public Nullable<bool> v16 { get; set; }
        public Nullable<bool> v17 { get; set; }
        public Nullable<bool> v18 { get; set; }
        public Nullable<bool> v19 { get; set; }
        public Nullable<bool> v20 { get; set; }
        public Nullable<bool> v21 { get; set; }
        public Nullable<bool> v22 { get; set; }
        public Nullable<bool> v23 { get; set; }
        public Nullable<bool> v24 { get; set; }
        public Nullable<bool> s1 { get; set; }
        public Nullable<bool> s2 { get; set; }
        public Nullable<bool> s3 { get; set; }
        public Nullable<bool> s4 { get; set; }
        public Nullable<bool> s5 { get; set; }
        public Nullable<bool> s6 { get; set; }
        public Nullable<bool> s7 { get; set; }
        public Nullable<bool> s8 { get; set; }
        public Nullable<bool> s9 { get; set; }
        public Nullable<bool> s10 { get; set; }
        public Nullable<bool> s11 { get; set; }
        public Nullable<bool> s12 { get; set; }
        public Nullable<bool> s13 { get; set; }
        public Nullable<bool> s14 { get; set; }
        public Nullable<bool> s15 { get; set; }
        public Nullable<bool> s16 { get; set; }
        public Nullable<bool> s17 { get; set; }
        public Nullable<bool> s18 { get; set; }
        public Nullable<bool> s19 { get; set; }
        public Nullable<bool> s20 { get; set; }
        public Nullable<bool> s21 { get; set; }
        public Nullable<bool> s22 { get; set; }
        public Nullable<bool> s23 { get; set; }
        public Nullable<bool> s24 { get; set; }
        public Nullable<bool> d1 { get; set; }
        public Nullable<bool> d2 { get; set; }
        public Nullable<bool> d3 { get; set; }
        public Nullable<bool> d4 { get; set; }
        public Nullable<bool> d5 { get; set; }
        public Nullable<bool> d6 { get; set; }
        public Nullable<bool> d7 { get; set; }
        public Nullable<bool> d8 { get; set; }
        public Nullable<bool> d9 { get; set; }
        public Nullable<bool> d10 { get; set; }
        public Nullable<bool> d11 { get; set; }
        public Nullable<bool> d12 { get; set; }
        public Nullable<bool> d13 { get; set; }
        public Nullable<bool> d14 { get; set; }
        public Nullable<bool> d15 { get; set; }
        public Nullable<bool> d16 { get; set; }
        public Nullable<bool> d17 { get; set; }
        public Nullable<bool> d18 { get; set; }
        public Nullable<bool> d19 { get; set; }
        public Nullable<bool> d20 { get; set; }
        public Nullable<bool> d21 { get; set; }
        public Nullable<bool> d22 { get; set; }
        public Nullable<bool> d23 { get; set; }
        public Nullable<bool> d24 { get; set; }

    }
}