//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoRobot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class horario
    {
        public int id_horario { get; set; }
        public Nullable<System.TimeSpan> hora_inicio { get; set; }
        public Nullable<System.TimeSpan> hora_fin { get; set; }
        public Nullable<bool> l { get; set; }
        public Nullable<bool> m { get; set; }
        public Nullable<bool> x { get; set; }
        public Nullable<bool> j { get; set; }
        public Nullable<bool> v { get; set; }
        public Nullable<bool> s { get; set; }
        public Nullable<bool> d { get; set; }
        public int id_tarea { get; set; }
    
        public virtual tarea tarea { get; set; }
    }
}
