//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoRobot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sistema_op_x_robot
    {
        public int id_robotsistema { get; set; }
        public int id_robot { get; set; }
        public int id_sistema { get; set; }
    
        public virtual robot robot { get; set; }
        public virtual sistema_operacional sistema_operacional { get; set; }
    }
}
